### ISSUE TITLE
Add type-safe headers

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#108]
I've had a couple of problems where I forgot to pass headers to my APIs, we could add this to add another level of type safety to ts-rest.

**Comment by michaelangrivera** [comment]
@oliverbutler I'd like to pick this up if no objections!

**Comment by oliverbutler** [comment]
@michaelangrivera Want to discuss the strategy for this in discord? Happy to help out, got some time :)

**Comment by kareemmahlees** [comment]
Newcomer here 👋🏻!
Any updates? I want to give a hand in this!

**Comment by oliverbutler** [comment]
@kareemmahlees - I think @michaelangrivera has been busy as of late, so let's ask him what he expects here!

As part of 3.18 we added the ability to add headers to the client libs, but it's not type-safe yet, @michaelangrivera do you want to continuing owning this or hang off if @kareemmahlees wants to give it a shot?

**Comment by oliverbutler** [comment]
I've been wondering about this since messaging, does this prove the need for a new initContract method? 🤔 

Could solve the problem of keeping headers DRY (wdyt @kareemmahlees  @michaelangrivera )

<img width="977" alt="Screenshot 2023-02-25 at 14 03 42" src="https://user-images.githubusercontent.com/47489826/221361162-c34d8ced-79aa-4f1b-8163-5df5447a1038.png">

**Comment by oliverbutler** [comment]
Or maybe two things `c.contract` and `c.endpoints`? I'm not sure if we want to allow multiple levels of headers

**Comment by michaelangrivera** [comment]
We should definitely give it to someone who has the time to get it rolling; I can assist with it for sure, but if you or @kareemmahlees want to take the lead, please do. I'm going to be swamped until April 5th 😢 

@oliverbutler So this new method would not replace the old `c.router` method, correct? 

I like the idea of a new method so that we do not have breaking changes, but people can migrate over if they'd like to (in this case it would be a simple copy and paste too). 
Would the `headers` key under `endpoints` override the types of the top level `headers` key? 

Perhaps it would be better to rename the top-level `headers` key to `defaultHeaders` or `baseHeaders` to make it clear those headers apply to everything in that contract. 

What about nested contracts and multiple contracts? Is the strategy to have business logic separated by contract? For instance, would a set of _private_ routes (that would require some user authentication headers like `Bearer`) go under one contract? And then the _public_ routes (that do not require auth) go under another contract?

**Comment by Gabrola** [comment]
@michaelangrivera Agree on both points, to not introduce any breaking changes, and also using a `baseHeaders` name.

What do you think of adding a second parameter to `c.router`? We can use that for options common between all endpoints. We can kill two birds with one stone here and introduce `jsonQuery` where it should really belong, as at the moment it needs to be manually enabled on both client and server.

To handle nested and multiple contracts with shared options we can introduce the idea of a baseContract and allow other contracts to extend it.

```typescript
const fullContract = c.router(
  {
    getPost: {
      method: 'GET',
      path: `/posts/:id`,
      responses: {
        200: c.response<Post | null>(),
      },
    },
  },
  {
    baseHeaders: z.object({
      'X-Auth-Token': z.string(),
    }),
    jsonQuery: true,
  }
);

const baseContract = c.base({
  baseHeaders: z.object({
    'X-Auth-Token': z.string(),
  }),
  jsonQuery: true,
});

const postsRouter = baseContract.router({
  getPost: {
    method: 'GET',
    path: `/posts/:id`,
    responses: {
      200: c.response<Post | null>(),
    },
  },
});
```

**Comment by kareemmahlees** [comment]
> I've been wondering about this since messaging, does this prove the need for a new initContract method? 🤔
> 
> Could solve the problem of keeping headers DRY (wdyt @kareemmahlees @michaelangrivera )
> 
> <img alt="Screenshot 2023-02-25 at 14 03 42" width="977" src="https://user-images.githubusercontent.com/47489826/221361162-c34d8ced-79aa-4f1b-8163-5df5447a1038.png">

I totally agree with this and this was actually my initial thought on this.

* First of all, because `contract` is far more expressive lol.
* Second, this allows for route-specific headers and global headers although we will need to parse the headers so, for example, the route-specific headers can override the global headers if the header key is present in both, although as @michaelangrivera stated we could change the global headers key to `globalHeaders` or `defaultHeaders` to distinguish them from the route-specific headers.
* Third, I think this offers the best straightforward way of setting simple headers! @Gabrola 's implementation is Ok but I think it is a bit of a hassle to have to do all of this to just set simple headers.

Drawbacks:
 * This will surely cause breaking changes but as @michaelangrivera also stated this should be a manner of simply copying and pasting

**Comment by Gabrola** [comment]
@kareemmahlees It's not just about passing simple headers. A nested contract needs to be able to access any base headers that are defined in a parent contract, so we need a way of passing the same base headers with each nested contract without having to copy-paste the same code into each contract. Otherwise we'd have to change all our client-side and server-side APIs to pass both the parent contract and nested contract.

**Comment by kareemmahlees** [comment]
> @kareemmahlees It's not just about passing simple headers. A nested contract needs to be able to access any base headers that are defined in a parent contract, so we need a way of passing the same base headers with each nested contract without having to copy-paste the same code into each contract. Otherwise we'd have to change all our client-side and server-side APIs to pass both the parent contract and nested contract. I've updated my code example to make this clearer.

Could you give an example of nested contracts so as to be on the same page with you?

**Comment by Gabrola** [comment]
> > @kareemmahlees It's not just about passing simple headers. A nested contract needs to be able to access any base headers that are defined in a parent contract, so we need a way of passing the same base headers with each nested contract without having to copy-paste the same code into each contract. Otherwise we'd have to change all our client-side and server-side APIs to pass both the parent contract and nested contract. I've updated my code example to make this clearer.
> 
> Could you give an example of nested contracts so as to be on the same page with you?

https://github.com/ts-rest/ts-rest/blob/main/libs/example-contracts/src/lib/contract-nested.ts

**Comment by RWOverdijk** [comment]
Hi! I'd like to preface my comment saying that I'll make some assumptions. If I'm wrong please just let me know.

I think I would add headers to the already existing contract format. This object currently already supports merging contracts so that would allow anyone to create a base contract for (for example) protected endpoints. It's part of a request and I think it makes more sense to keep that together wiith the query, body and responses. At some point typing becomes very difficult to do if you also want to enforce response headers for example. Stuff like base-headers means you need to have a way to omit headers for certain endpoints, which could be fine but just something to keep in mind as it can get messy.

I also think that a breaking change, if needed, wouldn't be a bad thing. This also allows tightening up the terminology in the same release. I think a codemod could do a lot of heavy lifting for an upgrade path.

Personally I'd like this feature primarily for openapi. Adding typing for headers would be nice, but a bit harder to do.
