### ISSUE TITLE
Parse response on the client

### ISSUE THREAD

**Issue by hzmmohamed** [ts-rest/ts-rest#175]
As far as I've looked in the code so far, I believe zod parsing of the response on the client is not implemented yet. Is there a reason for that?

**Comment by Gabrola** [comment]
Yes, validating and parsing a server response on the client is not really a common pattern. There is not much reason to run the zod parser on the client if you are already doing so on the server; all transforms run and extra properties are removed from the response before the client receives it. Traditionally, the client usually trusts that the server sends the correct data, and type-safety was achieved by having the client-side code re-implement or re-use the server side typescript interfaces.

Also this allows our client bundle to be much smaller. We technically only need the type-safety on the client-side at compile time so in the future we can really slim down the bundle size by not including the entire contract in the runtime bundle.

**Comment by thomaslaich** [comment]
I'm not sure I can agree with the above. Assume we have e.g. a server schema with a date property. Like so:

```typescript
const PostSchema = z.object({ message: z.string(), ..., createdAt: z.date() });
```

The server will stringify this, i.e., `createdAt` will be serialized into an ISO string. In the client, without any zod parsing, I will now have a property of e.g. `createdAt: '2023-03-13T17:01:10.481Z';`. That is, it will be of type `string` instead of `Date`.

zod parsing in the client would actually elegantly solve this problem by reconstructing the correct types on each property. Moreover, it would "just work" when using zod custom types for things like `luxon` or `moment` dates, or `decimal.js` decimals etc.

**Comment by somaraani** [comment]
I agree with @thomaslaich. Without parsing the response, you are forced to always use `string`  types in your contract for dates. While this works, and you can just reconstruct your date, it is likely you will be doing this every time you use a date which gets cumbersome. Being able to define `Date` in the contract and easily use it client side would be very useful.

@Gabrola would you consider adding an optional `parseResponse` parameter on the client for those who would find it useful? 

Alternatively having a way add that functionality in a custom `ApiFetcher`, but not sure if that's possible since the contract is not exposed there.

**Comment by somaraani** [comment]
For anyone having issues with enforcing type safety with `Date`, this is how I solved it. 

I was returning objects in my backend where types were dates, for example:

```
type Example = {
  date: Date
}
```

This would work if my contract defined `date: z.date()`, but then the front-end would think `date` was a `Date` object, when it was now serialized to a `string`, which would break type safety. However, if I set it as `date: z.string()`, returning my object would give an error on the back-end, unless I stringified my date explicitly every time.

My solution was to do something like this `date: z.date().transform(d => d.toString())`. Even though we never actually run the transform function, the contract type now enforces returning a `Date` server side, and the client knows the value it receives is a `string`. 

If anyone knows of a better way to handle this case please let me know.

**Comment by Gabrola** [comment]
@somaraani that is exactly how it should be done. Zod schemas have an "input" and "output" TS type, by using a transform you are setting the input type as `Date` and output type as `string`. In ts-rest we correctly infer either the input or output type to the server or the client depending on the context. So for responses, we expose the `input` type to the server, so in this case you are forced to return a `Date` object in your response object, and we expose the `output` type to the client.
We do the inverse on client to server data, so for query params, url params, body, headers, etc. the client has the `input` type and the server receives the `output` type.

This works nicely even if you don't let ts-rest parse your response, but it only works for one-way transformation where the types coincide with the default `.toJSON()` behavior of whatever you are transforming.

I think there is merit in the points raised by @thomaslaich, where we can do a two-way transformation, such that, in the case of Dates, you can cleanly pass a Date object on your server, and receive a Date object in your client. This isn't possible with Zod without unreliable hacks as Zod only defines a one-way transformation of `input` -> `output`. For example...

```typescript
date: z.union([z.string(), z.date()]).pipe(z.coerce.date()),
stringLen: z.union([z.string(), z.number()]).transform((val) => typeof val === 'string' ? val.length : val)
stringDouble: z.string().transform((s) => `${s}${s}`)
```

In this case, the transform works on the date if we run zod's `.parse()` on both the client and the server because mapping between a date and a string is an isomorphic transform, same goes for `stringLen` because we can determine the type, so the "transform" does not re-run on the client. But in the case of `stringDouble` this does not work because both the input and output type are a string, but we cannot do anything to prevent the transform from re-running on the client.

The only correct way to do this would be to provide a client-only or server-only transform field in the contract so that you can recover objects such Dates from strings or plain JSON objects.

**Comment by llllvvuu** [comment]
Is there any reasonable way to handle this in a way such that type inference is narrow (i.e. does not infer `string | Date`), without writing two schemas and two contracts, with duplicated TSDoc?

**Comment by firxworx** [comment]
@Gabrola I hugely disagree that "validating and parsing a server response on the client is not really a common pattern" especially in the exact types of applications where ts-rest is particularly well-suited: apps with a real _purpose_ such as business and enterprise apps.

For these sorts of applications, in general, accuracy, correctness, maintainability, development velocity, minimizing bugs and regressions, and principles like "fail fast" are top concerns. This is why TypeScript was created in the first place!

I agree that proper validation and parsing is not a common pattern _period_ but that's because the majority of code on the Internet is brittle and hacked together. Only a tiny, _tiny_ minority of all code in existence can be classified as remotely _professional_ and _production grade_ per the standards of any serious business or even personal project.

To illustrate this point in a lighthearted way, please consider the following arguments:

- ts-rest should no longer test its code because writting any tests whatsoever is not a common pattern
- ts-rest should just use `any` under the hood and fake type safety because that's the most common pattern
- ts-rest should be abandoned because it is not common to have a well-defined shared contract between client + server

Common will _never_ deliver on ts-rest's _mission_ to deliver _type safety_ via a contract-based approach!

Blind trust of types from external data sources (user, files, API's, _anything_) is often cited as a weak point of TypeScript/JavaScript and is a hugely common source of brittleness and regression bugs in any real world app.

The remedy for _real_ run-time type safety vs. the _illusion_ delivered by TypeScript, i.e. for TS to actually live up to its promise,  is none other than parsing and validating _all_ "data in".

Robust business systems have _zero trust_ for _anything_ coming in from outside _module boundaries_ including between different internal microservices/services, between any server + client applications, etc.

All said, I would kindly encourage you to reconsider. 

Please take note of us early adopters in ts-rest and how we see a need and are identifying this as a requirement. I would personally classify any situation where ts-rest types lie to the developer as a bug because it is represents a failure to deliver on the promise of type safety.

My $0.02 is client parsing vs the contract should be automatic and _opt-out_. IMHO if a user is working with data from a ts-rest client vs. a given contract, then ts-rest should _guarantee_ that the data is what it says it is.

**Comment by Gabrola** [comment]
@firxworx Thank you for input on this! I agree with you in principle on all points honestly; it's just that we have a couple of issues in practice.

- Zod schemas are not guaranteed to be isomorphic, so there will be possible loss of information during the parsing of the response. If response parsing and validation is enabled on the server-side, some zod `.transform()`s will result in a non-reversible transformation. Therefore, if parsing and validation are enabled again on the client-side, it might lead to validation errors or even incorrect data. For example a schema of ``z.string().transform((s) => `${s}${s}`)`` would result in the string being repeated four times when the parser is run twice. While, this seems like quite an unlikely usage of zod, we can not be sure of the current use-cases out in the wild in production, hence why `validateResponseOnClient` is opt-in.
- A common use-case is to include zod database schemas in the contracts, as a result the entire database schema is inadvertently included in the client-side bundle. While not necessarily a major security issue given we are not relying on security-by-obscurity, it can be an issue for leaking intellectual property. We've planned to tackle this by purging the schemas from the client-side bundle as the TS types are only needed at compile-time and not runtime. This is obviously mutually exclusive with enabling `validateResponseOnClient` but I believe we can support both moving forward, and the library users can pick what they need.

**Comment by hzmmohamed** [comment]
@firxworx Thank you for this input! Just wanted to add to your second to last point.

As someone trying out ts-rest, I basically assumed client-side parsing was already implemented, as this is technically the only way to guarantee type safety at runtime. I was quite suprised to not find it eventually.

I think most users would share this experience. The concerns such as bundle size or IP that @Gabrola mentioned affect a very small subset of users, which could then make use of the opt-out toggle. I suggest allowing an opt-out toggle for every endpoint separately. I think such flexibility would be desirable.

Thanks!

**Comment by msaspence** [comment]
For anyone stumbling on this looking for answers your want the `validateResponse` options when init'ing your client
