### ISSUE TITLE
Does class-validator supported ? 

### ISSUE THREAD

**Issue by blazespirit** [ts-rest/ts-rest#186]
Does this library have support for using [class-validator](https://github.com/typestack/class-validator) for validation instead of zod? I will be using NestJS and it have very solid integration using class-validator so I wonder if class-validator is supported. Thanks

**Comment by michaelangrivera** [comment]
I don't know if class-validator is on the roadmap for ts-rest. I'll discuss it with the team. 

In the meantime, as @RWOverdijk said, you can likely use `zod` to automatically parse the request data in your contract.

Here's a Nestjs example:
```
const c = nestControllerContract(contract.global)

  @TsRest(c.getUser)
  async getUser(
    @TsRestRequest() params: RequestShapes['getUser'],
    @Req() request: Request
  ): Promise<ContractResponses['getUser']> {
    c.getUserGlobal.query.parse(params.query)
```

For response validation, you can use https://ts-rest.com/docs/nest#response-validation

@Gabrola, do we know if the @TsRest decorator automatically validates incoming query and body params?

**Comment by Gabrola** [comment]
@michaelangrivera `@TsRestRequest` will only run validations if the contract is defined with zod schemas, but if it's just TS types, then it will only provide type safety without validation. You could technically do something like this

```typescript
  @TsRest(c.updatePost)
  async updatePost(
    @TsRestRequest() { params: { id }, body, query }: RequestShapes['updatePost'],
    @Body() _: UpdatePostDto,
    @Param() _: UpdatePostParams,
    @Query() _: UpdatePostQuery,
) {
  }
```

You can use the DTO types as part of the contract using `c.body<UpdatePostDto>()`, but it is kinda hacky, and will have an incorrect type if you do any transformations, exposes, excludes, etc. using `class-transformer` since it cannot infer any transformed types.

@blazespirit As @RWOverdijk said, give zod a spin, it's miles better in terms of DX.

I don't think class-validator aligns with our full type-safety goals, so I believe it'll never have first-class support in ts-rest

**Comment by Gabrola** [comment]
@michaelangrivera `@TsRestRequest` will only run validations if the contract is defined with zod schemas, but if it's just TS types, then it will only provide type safety without validation. You could technically do something like this

```typescript
  @TsRest(c.updatePost)
  async updatePost(
    @TsRestRequest() { params: { id }, body, query }: RequestShapes['updatePost'],
    @Body() _: UpdatePostDto,
    @Param() _: UpdatePostParams,
    @Query() _: UpdatePostQuery,
) {
  }
```

You can use the DTO types as part of the contract using `c.body<UpdatePostDto>()`, but it is kinda hacky, and will have an incorrect type if you do any transformations, exposes, excludes, etc. using `class-transformer` since it cannot infer any transformed types.

@blazespirit As @RWOverdijk said, give zod a spin, it's miles better in terms of DX.

I don't think class-validator aligns with our full type-safety goals, so I believe it'll never have first-class support in ts-rest

**Comment by samislam** [comment]
Is there any update on this 🙁
