### ISSUE TITLE
node16 (ESM) module resolution doesn't work

### ISSUE THREAD

**Issue by samuelstroschein** [ts-rest/ts-rest#188]
Hi there, 

Using @ts-rest in an ESM project that uses moduleResolution "node16" breaks typesafety:

<img width="1013" alt="CleanShot 2023-03-16 at 14 25 12@2x" src="https://user-images.githubusercontent.com/35429197/225630958-864f19a6-37e8-4a32-88c2-0637ea8de3a2.png">

### Additional information 

The project set up is overly complicated, making it harder to contribute.

- @ts-rest is "type: module" but the tsconfig in core uses commonjs for module resolution
- the exports field references a different declaration file `./src/index.d.ts` instead of the declaration file (which is not created, why not?) of `./index.js`
- npm does not work, pnpm is required
- `pnpm i` takes several minutes 
- the nx setup seems overkill for a simple library

**Comment by samuelstroschein** [comment]
Yeah... the project setup is way too complex for a "simple" library. 

I looked into opening a PR but immediately ran into 

```
Incompatible tsconfig option. Module resolves to 'Node16'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.
```

### Problems

1. There is no need for rollup to publish npm packages (anymore). 
2. Now I understand why this project uses different type declarations (which likely contributes to the issue). Rollup is the root cause.

### Proposal

1. Get rid of rollup, just use the typescript cli `tsc`. 
2. Get rid of babel. The consumers use bundlers anyways which will polyfill based on _their requirements_. 
3. (NX is overkill. This project could likely use npm/pnpm workspaces.)

**Comment by michaelangrivera** [comment]
Hi @samuelstroschein, thank you for the input. 

So we focus on the core issue, can you provide us a small example repo that replicates the issue? Thank you.

**Comment by samuelstroschein** [comment]
Hi @michaelangrivera, 
Here is a stackblitz repro https://stackblitz.com/edit/typescript-hbf8ry?file=index.ts. Changing the typescript module and moduleResolution values fixes the issue. 

Node16 module (resolution) is the JS standard.

**Comment by Gabrola** [comment]
@samuelstroschein thanks for raising this issue! The fix for this is in and we can hopefully release it soon. "type: module" was being incorrectly added by the NX rollup library by default but we shouldn't since ts-rest's TS code is not in ESM.

Regarding the points about contribution

We need a monorepo task runner like NX/turborepo because we have many dependencies between the internal packages, the example apps/packages which we use for integration testing, and our docs website which also depends on the compiled libraries. So NX easily handles running our builds and tests in correct order while also caching outputs to make subsequent executions much faster. 

Regarding the use of rollup, yes technically it's not needed, the alternative would be running `tsc` twice to transpile into CJS and ESM files separately, but rollup is easier to setup and is what NX is using by default for publishable libraries. Otherwise we'd have to setup multiple `tsc` build tasks with separate tsconfig.json files to get the job done.

We are not using babel to compile any of the libraries, it's there for the docusaurus docs website.

You can't use npm because the project is using pnpm; they are not interchangeable. You are always stuck with whatever the project already uses. pnpm is objectively faster and better though 😄

**Comment by samuelstroschein** [comment]
@Gabrola Thanks for the in-depth reply. Your repo, your choice. Feel free to ignore everything below :)

If you want ts-rest to reach wider adoption and more contributions, I recommend streamlining this repo. Rollup, Prisma, NX, the `tools` directory, docker, jest seem all redundant for a simple library. 

Simple 2023 monorepo/ts stack: 

- only use tsc 
- npm/pnpm workspaces with turborepo (because just npm scripts that everyone is familiar with. NX is too complicated)
- vitest for 0 setup testing

**Comment by Gabrola** [comment]
See #204
