### ISSUE TITLE
@ts-rest/react-query not working with `select` property

### ISSUE THREAD

**Issue by Riley-Brown** [ts-rest/ts-rest#289]
A nice feature of `@tanstack/react-query` is the ability to pass a `select` property when working with nested data. However, using `select` with `@ts-rest/react-query` `initQueryClient` does not seem to respect the select property

### Usage with regular `useQuery`

```ts
  const { data } = useQuery({
    queryKey: [router.query.brokerId],
    queryFn: () =>
      brokersClient.getBroker({
        params: { _id: router.query.brokerId as string },
      }),
    select: (data) => {
      if (data.status === 200) {
        return data.body.data
      }

      return data
    },
  })
```
react query is able to properly change the type of `data` here based on the select function

###  Usage with `initQueryClient`

```ts
  const { data } = brokersClient.getBroker.useQuery(
    [router.query.brokerId],
    { params: { _id: router.query.brokerId as string } },
    { select: (data) => data.body.data }
  )

```

`select` gives a type error here for the return value and the type of `data` does not reflect what is selected from `select`

![image](https://github.com/ts-rest/ts-rest/assets/38029101/2ecdbad8-7db0-4de0-b561-ff99edb5d63f)

**Comment by julienmonnard** [comment]
Hello! This issue is quite old, so not sure if the reason behind it is the same, but it's definitely still happening.

It's a bit hard to pinpoint exactly where the cause is, because I don't know the code of the repo very well, and my TS knowledge is not the best. But I think the problems are around https://github.com/ts-rest/ts-rest/blob/56b955f82118e251a13b1e8766f25ca02e91356a/libs/ts-rest/react-query/src/lib/inner-types.ts#L115 and https://github.com/ts-rest/ts-rest/blob/56b955f82118e251a13b1e8766f25ca02e91356a/libs/ts-rest/react-query/src/lib/types.ts#L34

I will try to detail a bit more:

When you follow the types on the links above, you can see that the `TanStackUseQueryOptions` is called with a single type argument.

The `UseQueryOptions` type from the library can take 4 arguments, that are `TQueryFnData`, `TError`, `TData` and `TQueryKey`. By default,  the first two are unknown, and `TData = TQueryFnData`.

The problem when you give `UseQueryOptions` only the first argument, is that it will stop the type inference, and force TData to its default.

For the `select` here, its type is `select?: (data: TQueryData) => TData`. But assuming my explanation above makes sense, it currently translates to `select?: (data: TQueryData) => TQueryData`.

I got this from this article: https://tkdodo.eu/blog/react-query-and-type-script#partial-type-argument-inference 

Not sure what the proper fix would be, but probably at least either not provide any argument, or all of them.
