### ISSUE TITLE
Can you manually specific a query or mutation in the contract?

### ISSUE THREAD

**Issue by tomfrew** [ts-rest/ts-rest#292]
Hi,

We have an json-RPC API where all requests are POST requests. Is there a way to manually specify if the request is a query or a mutation rather than inferring from GET/POST?

Thanks!

**Comment by ivan-dalmet** [comment]
Same here, the (bad) api is using a GET for a endpoint but it's a mutation 😅
Any idea how we can declare manually the query or mutation type when we have a bad api design? 😅

**Comment by michaelangrivera** [comment]
(This is a hack) You could make your entire HTTP contract implementation POST. I would presume this would solve your issue. 

Take for instance, this contract:
```typescript
export const apiBlog = c.router(
  {
    createPost: {
      method: 'POST',
      path: '/posts',
      responses: {
        201: PostSchema,
      },
      body: z.object({
        title: z.string().transform((v) => v.trim()),
        content: z.string(),
        published: z.boolean().optional(),
        description: z.string().optional(),
      }),
      summary: 'Create a post',
    },
    getPost: {
      method: 'GET',
      path: `/posts/:id`,
      responses: {
        200: PostSchema,
        404: z.null(),
      },
      query: null,
      summary: 'Get a post by id',
    },
````
You would change all the methods to `POST`. Resulting contract:
```
```typescript
export const apiBlog = c.router(
  {
    createPost: {
      method: 'POST',
      path: '/posts',
      responses: {
        201: PostSchema,
      },
      body: z.object({
        title: z.string().transform((v) => v.trim()),
        content: z.string(),
        published: z.boolean().optional(),
        description: z.string().optional(),
      }),
      summary: 'Create a post',
    },
    getPost: {
      method: 'POST', // <- change to POST
      path: `/posts/:id`,
      body: z.object({}) // <- blank body
      responses: {
        200: PostSchema,
        404: z.null(),
      },
      query: null,
      summary: 'Get a post by id',
    },
````

**Comment by Gabrola** [comment]
We are purposely only exposing `useQuery` on GET requests and `useMutation` to prevent any inadvertent app bugs assuming the API is properly RESTful. Running non-GET requests in a query can be pretty dangerous in some cases as refetches and retries are a core part of tanstack query, and RESTful POSTs are by-design non-idempotent.

There is a workaround you can do that's left up to the user to use in edge-cases where you use tanstack's regular `useQuery` and run `client.mutate(...)` inside the `queryFn` or vice-versa to run a query inside a mutation. 

```typescript
import { tsRestFetchApi, PartialClientInferRequest } from '@ts-rest/core';
import { initQueryClient, UseMutationResult, UseQueryOptions, UseQueryResult } from '@ts-rest/react-query';

const client = initQueryClient(contract, {
  baseHeaders: {},
  baseUrl: 'https://api.com',
  api: async (args) => {
    const result = await tsRestFetchApi(args);

    if (!String(result.status).startsWith('2')) {
      throw result;
    }

    return result;
  }
});

const mutation = useMutation((args: PartialClientInferRequest<typeof contract.exampleQuery>) => {
  return client.exampleQuery.query(args);
}) as UseMutationResult<typeof contract.exampleQuery, typeof client>;

const query = useQuery(['QUERY_KEY'], () => {
  return client.exampleMutation.mutate(...);
}) as UseQueryResult<typeof client.exampleMutation>;
```

@tomfrew I'm a little confused as AFAIK, json-rpc uses a single endpoint, so I'm not sure how ts-rest fits here. Since json-RPC is not REST so it's outside of the scope of ts-rest. Either way, in case you have a lot endpoints that are all defined as POST, the above solution would be quite a hassle.

However there's a workaround that's a little hacky, but should be pretty simple and it takes advantage of the fact that we actually have the `useQuery` and `useMutation` functions available at runtime but not exposed through the TS types. So you can actually just cast the ts-rest client to a custom type.

```typescript
import { PartialClientInferRequest } from '@ts-rest/core';
import { initQueryClient, UseMutationResult, UseQueryOptions, UseQueryResult } from '@ts-rest/react-query';

type AddUseQueryToClient<T> = {
  [TKey in keyof T]: T[TKey] extends {
    useMutation: (
      ...args: any[]
    ) => UseMutationResult<infer TAppRoute, infer TClientArgs>;
  }
    ? TClientArgs extends ClientArgs
      ? T[TKey] & {
          useQuery: (
            queryKey: QueryKey,
            args: PartialClientInferRequest<TAppRoute, TClientArgs>,
            options?: UseQueryOptions<TAppRoute>
          ) => UseQueryResult<TAppRoute>;
        }
      : never
    : T[TKey] extends { useQuery: any }
    ? T[TKey]
    : AddUseQueryToClient<T[TKey]>;
};

const client = initQueryClient(...);
const clientWithUseQuery = client as AddUseQueryToClient<typeof client>;
```

I don't think we'd prefer to provide first-class support for non-REST or badly designed REST APIs, so I'll treat the above workarounds as the solution. Feel free to discuss this further.
