### ISSUE TITLE
getQueryData method expects queryClient as first argument and returning the incorrect cached item

### ISSUE THREAD

**Issue by jeremysylee** [ts-rest/ts-rest#344]
I've seen the following examples in various places (as documented [here](https://ts-rest.com/docs/react-query) and [here](https://github.com/ts-rest/ts-rest/blob/f30f72bf7df637eeae7f6e28f9532513686ca724/apps/docs/docs/react-query.mdx#L217)) and it appears to work correctly.
```
      const cachedFeedData = client.users.getFeed.getQueryData(['feed']);
```
cachedFeedData is the correct data and is properly typed. However, typescript is throwing an error. 
```
Expected 2-3 arguments, but got 1.ts(2554)
inner-types.d.ts(48, 93): An argument for 'queryKey' was not provided.
(property) getQueryData: (queryClient: QueryClient, queryKey: QueryKey, filters?: QueryFilters | undefined) => {...}
```

If I pass in the queryClient as the first argument and the keys as the second, I get data back which is typed according to the route like before, however, the data that is returned is from a different query altogether. 

```
      const cachedFeedData = client.users.getFeed.getQueryData(queryClient, ['feed']);
```

**Comment by michaelangeloio** [comment]
@jeremysylee can you provide a minimal reproduction example repo? 

Not sure what the data looks like that you're getting back? 

I haven't ran into this issue before.

**Comment by Gabrola** [comment]
@jeremysylee this is very weird, your first example should not work at all, even at runtime. In order to not have to pass the query client, you need to initialize a client in the top level of your component by doing

```typescript
const apiQueryClient = useTsRestQueryClient(client);

// somewhere
const cachedFeedData = apiQueryClient.users.getFeed.getQueryData(['feed']);
```

Can you double-check your code, and make sure the query keys are consistent and correct. If you are still getting incorrect data, can you share a repro or at least a full code sample so we can check?

**Comment by Gabrola** [comment]
Stale
