### ISSUE TITLE
ReactQueryClient queryKey simplification

### ISSUE THREAD

**Issue by stychu** [ts-rest/ts-rest#381]
Would it be possible to abstract reactQuery key'ing for api calls? Similar how tRPC does it so you don't have to keep the list or queryKeys anywhere but ts-Rest would automatically handle this.

https://ts-rest.com/docs/react-query#usequery-and-usemutation

instead of this
```ts
const queryResult = client.posts.get.useQuery(
  ['posts'], // <- queryKey
  { params: { id: '1' } },
  { staleTime: 1000 }
);
```

to have this

```ts
// no queryKey as this should automatically inject unique identifier for the call
const queryResult = client.posts.get.useQuery(
  { params: { id: '1' } }, 
  { staleTime: 1000 } 
);
```

**Comment by michaelangeloio** [comment]
hi @stychu, unless @oliverbutler disagrees I think this feature is out of scope for ts-rest. We try to be un-opinionated on the dependencies we incorporate and be close to the original dependency's API, especially for react-query.

**Comment by Gabrola** [comment]
This should be possible, as theoretically all the params that uniquely identify a query are passed in the hook function call. So in this example ts-rest could create a query key that looks something like `['/posts/:id', { params: { id: '1' } }]`. So despite this being out of ts-rest's scope, it seems like ts-rest is well-equipped enough to abstract away query keys.

However, as @michaelangeloio mentioned this would be very opinionated and would make certain use cases a bit confusing. For example, if you manually set keys to something like `['posts', 1]` and then you want to say invalidate all queries for all post queries regardless of the id by doing `queryClient.removeQueries({ queryKey: ['posts'] })`. Something like this would be a bit challenging to do due to the abstraction and usage of objects inside the query key rather than just strings and numbers.

Furthermore, in some cases you might have params that you do not want to affect the query caching behavior. For example if you use headers for pagination, then this should be included in the query key, but something like an access token header should not be included in the query key. We can obviously introduce functionality to control this behavior, but in my opinion needs more cognitive effort to do correctly compared to constructing query keys manually.
