### ISSUE TITLE
RFC: Add an option to auto-filter fields not listed in the response schemas on the server

### ISSUE THREAD

**Issue by GabeAtWork** [ts-rest/ts-rest#382]
# Problem statement

At the moment, as long as the route handler responds with data fulfilling the schema type requirements, this data gets returned as is, even if it contains more fields than listed in the response schemas/types. For many use cases this is fine, but when working on public APIs, being able to control what data gets exposed is a must-have.

# Proposal

Add a new option on `c.router`, called `stripResponseContentUnrecognizedFields`, which if `true` will run the schemas with the `strip` option (doc here: https://github.com/colinhacks/zod#strip), resulting in fields not listed in the schema to be removed.

If only a type is provided and not a schema, this option won't do anything.

Here's an example:

```ts
// Example contract
export const contract = c.router({
  getPost: {
    method: 'GET',
    path: '/post/:id',
    responses: {
      200: z.object({
        name: z.string(), 
      })
    }
  }
});

// Route implementation
export const getPostHandler = async ({params: {id}}) => {
  // Here post has a `createdAt` field
  const post = await fetchPost();

  return {status: 200, body: post};
}
```

Currently, calling this endpoint would return:
```json
{
  "name": "Some name",
  "createdAt": "2023-09-04"
}
```

With this new option, it would return:

```json
// Only fields listed in the schema are present
{
  "name": "Some name"
}
```

**Comment by fruchtzwerg** [comment]
Perhaps I'm missing some context but isn't this already possible by wrapping the body in `Schema.parse()`?
The contract should already warn me if I'm using the wrong schema. It only requires the schemas to be refactored into a shared library, which probably makes sense anyways.

It also feels a bit weird to be forced to explicitly activate something that Zod does by default since ts-rest is using zod under the hood.

I think it would be more useful to de-/activate zod parsing as a whole with a switch and then just using the schemas as defined. This would give us full control in userland, whether we want to `strip()` or `passthrough()` any given response. It would also behave more expectedly in accordance with zod itself.
I'm not doing much backend work these days but I can't think of a use case where I'd want to strip but not validate a response - especially with public APIs outside of my control.

Also this is likely already covered by #306. I haven't tried this but is there a reason one could not use ts-rest as a REST client on the server as well?
```ts
const post = await fetchPost();
```
becomes something like this:
```ts
const client = initClient(contract, {
  validateResponseOnClient: true
})
const post = await client.getPostFromPublicAPI()
```

If I'd be building a library like this for work, I'd argue that the additional headache of maintaining, testing and documenting a feature like this, which is already possible through other means is not worth the effort.

Outside of these concerns I do think that having more options on how ts-rest handles data is a good thing. I'm merely suggesting to do so in a more abstract way rather than introducing more special cases for the team to maintain.

**Comment by GabeAtWork** [comment]
@fruchtzwerg you're making a good point, users can already do this by making individual schemas `strict()` or `strip()`. The proposal is more about having an easy way to set a "global policy" for a whole contract, so that users don't have to check each individual schema to make sure they don't accidentally leak more fields than intended.

Of course, while adding this global policy option is probably not that much work, someone is bound to come at some point saying "I'd like to have a global policy, but with a couple exceptions" and then complexity is creeping up if you start addressing this kind of request.

All this makes me think that the proposal can be refined:

Add a new option on `c.router`, called `nonRecognizedResponseFieldsPolicy`, with the following values:
- `none`: default policy, won't do anything with regards to non-recognized fields
- `strip`: run all response schemas with the `strip` option (doc here: https://github.com/colinhacks/zod#strip), stripping non-recognized fields silently
- `strict`: run all response schemas with the `strict` option (doc here: https://github.com/colinhacks/zod#strict), throwing if non-recognized fields are passed

**Comment by fruchtzwerg** [comment]
@GabeAtWork Makes sense. I'd still advise caution to not clutter the ts-rest options with too many global fields that do specific things. These have a tendency to get out of control as a library grows.

A more generic way to do this could be to allow a transform function to be passed that will automatically wrap any response
similar to the `api` field in `initClient()`. ts-rest could additionally provide a small helper directly so the configuration would look something like this:
```ts
import { stripResponse } from '@ts-rest/core';

export const contract = c.router({
  getPost: {
    method: 'GET',
    path: '/post/:id',
    responses: {
      200: z.object({
        name: z.string(), 
      })
    }
  },
  transform: stripResponse
});
```

As I'm writing this I realise that this is probably also possible with a global middleware/interceptor after registering the router.
Maybe I'm just overthinking it ¯\_(ツ)_/¯.

In any case I like your revised proposal better; it is more flexible and more explicit.
I'd change the naming to `additionalResponsePropertiesPolicy` to keep it in line with [OpenAPI](https://swagger.io/specification/v3/?sbsearch=additionalProperties) which itself derives the name from [JSON Schema](https://json-schema.org/understanding-json-schema/reference/object.html?highlight=additionalproperties#additional-properties).

**Comment by Gabrola** [comment]
You can already do this by enabling response validation. You can find the documentation for that in the respective server library documentation on the website.

By default zod strips extra keys when they run through the parser, you can control this behavior for individual responses by marking the objects with `.passthrough()`, `.strip()`, or `.strict()`
