### ISSUE TITLE
Using @Res with `multi-handler` with more than one method crashes

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#425]
Haven't had time to flesh this one out, but i wrote a failing test 

https://github.com/ts-rest/ts-rest/commit/85e942d4136910cdd510779181ed8313de1f46c0

```ts
@Controller()
        class MultiHandlerTestController {
          @TsRestHandler(contract)
          resTest(
            @Res() res: NestResponse
          ) {
            return tsRestHandler(contract, {
              redirectTest: async () => {
                console.log('res from redirectTest', res)

                res.redirect("https://ts-rest.com")

                return {
                  status: 302,
                  body: null
                }

              },
              otherEndpoint: async () => {
                console.log('res from otherEndpoint', res)

                return {
                  status: 200,
                  body: {
                    message: 'ok'
                  }
                }
              }
            });
          }
        }
```

**Comment by JanVanBraeckel** [comment]
This problem doesn't seem to be specific to multi-handler. It also happens when injecting `@Res()` in a single-handler and not using res.send(...)

```ts
@TsRestHandler(search)
searchHandler(@Res() res: Response) {
  return tsRestHandler(search, async () => {
    return {
      status: 200,
      body: response,
    };
  });
}
```

It seems to be because using `@Res()` puts the endpoint into "library mode" and requires the consumer to issue a response by using res.send(...) or res.json(...)

This is documented on https://docs.nestjs.com/controllers#request-object
> Note that when you inject either `@Res()` or `@Response()` in a method handler, you put Nest into Library-specific mode for that handler, and you become responsible for managing the response. When doing so, you must issue some kind of response by making a call on the response object (e.g., res.json(...) or res.send(...)), or the HTTP server will hang.

However, I'm not sure this is something ts-rest can fix, because even if we could detect if the method handler uses `@Res()`, issuing a response for the request would mean that following interceptors in the interceptor chain can't edit the response anymore.

**Comment by Gabrola** [comment]
@JanVanBraeckel You are correct! You should always use `@Res({ passthrough: true })` with ts-rest and not `@Res()`
