### ISSUE TITLE
Next 14?

### ISSUE THREAD

**Issue by twobit** [ts-rest/ts-rest#428]
I'd like to try out `ts-rest/next` in a Next 14 project but it looks like it's not yet supported:

```
{
  "name": "@ts-rest/next",
  "version": "3.30.4",
  "peerDependencies": {
    "next": "^12.0.0 || ^13.0.0",
    "zod": "^3.22.3"
  },
```

**Comment by michaelangeloio** [comment]
@twobit you can actually get away with using most of TS-rest via the @ts-rest/core package (since most data fetching is done via server actions and server components). Were you planning on using ts-rest in API handlers? 

I think we're still thinking of use cases since Nextjs has most data fetching through server components now (13+).

**Comment by ssijak** [comment]
`I think we're still thinking of use cases since Nextjs has most data fetching through server components now (13+).` 

That is if the project adopts that approach. I would wager that most projects do not.
Pages directory is still supported (and they said they have no plan to stop supporting it).
All that to say that there is no reason to not bump next to 14 in peerDeps

**Comment by hichemfantar** [comment]
I think next 14 doesn't actually breaks any of the existing behavior in the pages router, the major 14 version bump is mostly marketing anyway.
I agree with @ssijak in supporting 14 and it shouldn't break anything.
