### ISSUE TITLE
Optional query parameter in contract is not optional in client

### ISSUE THREAD

**Issue by jalric** [ts-rest/ts-rest#460]
Considering the current contract:
```javascript
export const contract = c.router({
  getPosts: {
    method: "GET",
    path: `/posts`,
    query: object({ foo: string() }).optional(),
    responses: {
      200: PostSchema.nullable(),
    },
  },
});
```
<br>

Why can't I just do?
```javascript
const { body, status } = await client.getPosts();
```

<img width="350" alt="Capture d’écran 2024-01-03 à 13 00 00" src="https://github.com/ts-rest/ts-rest/assets/807169/652be626-81e8-4b8f-98fe-74b217982e6d">
  
<br><br>
  
Of course the next example works, but it's unnecessarily verbose.
```javascript
const { body, status } = await client.getPosts({ query: {}});
```

**Comment by michaelangeloio** [comment]
I believe that's because, at the root, the `query` still expects an object (albeit it is empty). I think this would be an enhancement, but I advise against abstraction like this (or "magic"), as they call it.

**Comment by Gabrola** [comment]
If all individual query parameters are marked as optional, then the query object itself will become optional when calling from the client.

Semantically it doesn't make sense to mark the entire query schema as optional because we always pass a query object, which may be empty but it still always exists.
