### ISSUE TITLE
`@ts-rest/react-query|core` - Strict Status Codes for Typed Errors

### ISSUE THREAD

**Issue by christos97** [ts-rest/ts-rest#471]
## Description
I've encountered a potential bug or unintended behavior using the ts-rest/react-query|core libraries together, 
Specifically relating to the `strictStatusCodes` setting in a REST API contract. 
The issue arises when strictStatusCodes is set to `true`. 
According to the documentation (?) (or logical expectation), setting `strictStatusCodes` to `true` should restrict error responses to only those status codes `explicitly `mentioned in the contract (4xx and 5xx). 

However, the current implementation seems to return all status codes, including 200 and undefined.

## Expected Behavior
When strictStatusCodes is set to true, the error status should strictly adhere to the 4xx and 5xx status codes defined in the API contract. Other status codes, particularly successful ones like 200, should not be included in the error status.

## Current Behavior
The implementation of strictStatusCodes is not limiting the error status to the specified 4xx and 5xx codes. Instead, it is capturing all possible status codes, including 200 and undefined (already strictly and correctly defined in the `data` object).

Steps to Reproduce
Define a contract with strictStatusCodes set to true.

Set up endpoints in the contract with specific 4xx and 5xx error codes.
Observe that error.status includes status codes outside the defined 4xx and 5xx range, such as 200 and undefined.

In the screenshot below, expect the desired  behaviour to be of type ApiError in body (which works fine),
but the error.status should only take 403 (not even undefined imho), since data.status is either data undefined or status = 200.

The `error` object of react-query response should ideally strictly contain the error code(s) provided in the contract, if it exists.

If I'm doing anything wrong, please let me know :)

Thanks for your help in advance and keep up the good work. 
I really love this project, working with it in NX monorepos is a no-brainer
Kudos :100: 

![Screenshot from 2024-01-12 01-17-15](https://github.com/ts-rest/ts-rest/assets/25861552/42d34d29-6cff-49f9-abd5-a9e4013e6697)

**Comment by christos97** [comment]
I forgot to mention the dependencies (also, typescript v5.3.3)

```json
"dependencies": {
    "@tanstack/react-query": "4.33.0",
    "@ts-rest/core": "^3.33.0",
    "@ts-rest/express": "^3.33.0",
    "@ts-rest/react-query": "^3.33.0",
    "express": "4.18.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "zod": "^3.22.4",
    "tslib": "^2.6.2"
    ...
  }
```

**Comment by Gabrola** [comment]
Working as intended. `strictStatusCode` has no effect with react-query because, strict status codes are by default enabled for success statuses and ignored for errors because servers, load balancers, proxies, etc. can often throw errors that are not under control of your application.

**Comment by sebastienne** [comment]
Sorry, but that doesn't make sense, since exactly the same can be said when using the client from `@ts-rest/core`, and it adheres to `strictStatusCodes` for error responses. We're talking about a typing issue here, and if by definition of the contract my api only returns 400 error responses, the `@ts-rest/query` client should respect that, even if my application doesn't. The onus rests on me that it indeed does. Why would the error responses differ based on _how_ the data is being queried? It even looks like both clients use the same fetch-api under the hood (granted I've just glanced over their respective implementations).

Btw, I've patched [the line](https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/react-query/src/lib/types.ts#L31) I mentioned in my [original issue](https://github.com/ts-rest/ts-rest/issues/407) in the `@ts-rest/react-query` package, and it's been working just fine, but like I said back then, I can't be sure of it's original intent. If it's being ignored because of errors not under control of my application, then it really shouldn't be ignored at all.

Just to be clear, this issue is minor given the immense value `ts-rest` brings. Maybe the docs should simply state that the `@ts-rest/react-query` ignores `strictStatusCodes` for error responses.

**Comment by Gabrola** [comment]
@sebastienne Let me give you a bit of context, `strictStatusCodes` was introduced to indicate that a `contract` is "complete", and it forces the server to only respond with statuses defined in the contract. Without it, a server can respond with any status code outside of the ones defined, and it would not trip any type checking or run any runtime validations.

On the vanilla-client-side, `strictStatusCodes` should be combined with `throwOnUnknownStatus` such that you achieve parity between the runtime behavior and the TS types. This is not possible with `@ts-rest/react-query` because there is nothing beyond already triggering an error. In other words we can't have a `data` object, `error` object, and `unexpectedError` object.

Taking that into consideration, a strict status code on the `error`, is flat out incorrect typing in essentially _all_ cases. We can't just say the onus is on the developer using `strictStatusCodes` to ensure that the application does not return errors not defined in the contract, simply because it's not even fully in a developer's control. You can never 100% ensure that you will not receive an unexpected 4xx/5xx errors.

But yes, I agree with you that the docs might need some work.

**Comment by Gabrola** [comment]
@sebastienne Let me give you a bit of context: `strictStatusCodes` was introduced to indicate that a `contract` is "complete", and it forces the server to only respond with statuses defined in the contract. Without it, a server can respond with any status code outside of the ones defined, and it would not trip any type checking or run any runtime validations.

On the vanilla-client-side, `strictStatusCodes` should be combined with `throwOnUnknownStatus` such that you achieve parity between the runtime behavior and the TS types. This is not possible with `@ts-rest/react-query` because there is nothing beyond already triggering an error. In other words we can't have a `data` object, `error` object, and `unexpectedError` object.

Taking that into consideration, a strict status code on the `error`, is flat out incorrect typing in essentially _all_ cases. We can't just say the onus is on the developer using `strictStatusCodes` to ensure that the application does not return errors not defined in the contract, simply because it's not even fully in a developer's control. You can never 100% ensure that you will not receive an unexpected 4xx/5xx errors.

But yes, I agree with you that the docs might need some work.
