### ISSUE TITLE
Replace `c.noBody()` with `z.void()`/`c.type<void>` for empty request/response body

### ISSUE THREAD

**Issue by toteto** [ts-rest/ts-rest#555]
**Is your feature request related to a problem? Please describe.**

The #547 brought great fix that allows empty requests/responses, but there are few shortcomings of this solution:

- No runtime validation. The body is required to be empty, but the actual request/response may contain body, it will be ignored and validation will be performed.
- Optional body. For one or another reason a application might want to have `body: z.union([z.void(), z.object({msg: z.string()})])`. 
- Requests yet another library concept that developers have to read and thing about when designing the API. 

**Describe the solution you'd like**

Deprecate/remove the `c.noBody` in favour of `z.void()` and `c.type<void>`.

**Additional context**

Think it is OK for v3.x, maybe candidate for v4.x?

**Comment by Gabrola** [comment]
Using `void` was actually just a hack to get empty bodies to work, but semantically it makes no sense. `void` should only refer to a function that has no return value (but accepts `undefined` because in reality void functions return `undefined`). Validations are intended to run against an already existing body, but not validate its existence. If a route responds with or accepts no body, there's no need to run any validations.

There is no need to do runtime validations anyway because the body will be ignored in all cases anyway, ie: if you return a body from a route that should return no body, it will be ignored and not sent in the response. Therefore we've achieved runtime safety and type safety.
`z.noBody()` is needed because it controls the behavior on the server, and we can easily document this behavior. This isn't achievable with `c.type<...>()`, and using a Zod schema will be confusing because you would not expect it to change any behavior, and also introduces a runtime dependency on Zod in the core library.
