### ISSUE TITLE
Middleware/Plugins

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#57]
Middleware would be a great addition to @ts-rest.

I'm not sure how this should look yet in terms of the API, any feedback from usage would me massively appreciated :)

**Comment by ecyrbe** [comment]
Maybe i think it wrongly, but since you have different backends,
- nestjs: adding a middleware above it would not make much sense
- express: it's a really rich ecosystem, relying on it's already existing middleware should be encouraged

if you plan on adding it for other frameworks (oak, fastify, etc), then yes, you might want to add some.  
If so, i would try to add these frameworks from ts-rest and make them a config thing.  
Like remix did with their adapters :   
https://remix.run/docs/en/v1/other-api/adapter
  
Then implement your own middleware, knowing it will be harder to create a new ecosystem instead of reusing an existing one.

**Comment by oliverbutler** [comment]
Yup I tend to agree here, just implemented multipart form data. It's definitely easier to allow users to plug into their framework directly, completely skip out ts-rest from the equation!
