### ISSUE TITLE
serverless/next: Return 405 Method Not Allowed for methods that are not being implemented

### ISSUE THREAD

**Issue by digitex** [ts-rest/ts-rest#612]
For Next.js with App Router, any unimplemented methods will return 404 instead of 405:

Taking example from [https://github.com/ts-rest/ts-rest/blob/main/apps/example-next/](https://github.com/ts-rest/ts-rest/blob/main/apps/example-next/)

```
import { initContract } from '@ts-rest/core';
import { z } from 'zod';

const c = initContract();

export const testContract = c.router(
  {
    test: {
      method: 'GET',
      path: '/test/:id',
      pathParams: z.object({
        id: z.coerce.number(),
      }),
      query: z.object({
        foo: z.string(),
        bar: z.number(),
      }),
      responses: {
        200: z.object({
          id: z.number(),
          foo: z.string(),
          bar: z.number(),
        }),
      },
    },
  },
  {
    strictStatusCodes: true,
  },
);
```

POST request to /test/:id will return HTTP 404:

```
{
  "message": "Not Found"
}
```

**Comment by LudovicGen** [comment]
I think it's the optimal default behavior to use a 404 response for security reasons, so as not to disclose the HTTP methods available for a given route.

**Comment by Gabrola** [comment]
Agree with @LudovicGen. Also with how the routers are implemented, there's no quick way to match an existing path, but for a non-existent method. We'd have to manually add routes for the missing methods, in order to serve up the 405 response, which would just render the entire router slower.

We can't change this anyway, because it would be a breaking change. If you want to serve 405's you can just add them manually for now.
