### ISSUE TITLE
Wrong ESM exports

### ISSUE THREAD

**Issue by TheAsda** [ts-rest/ts-rest#614]
### Describe the bug

I'm using open-telemetry instrumentation with esm that is using `import-in-the-middle` library. The library parses output from each module and proxies every export to give ability to patch. 

### How to reproduce

1. Use esm in node
2. Register `import-in-the-middle`
3. Try to use `@ts-rest/fastify` or `@ts-rest/core`

### Expected behavior

I guess it's happening because of wrong "exports" fields. If i delete "exports" field everything works fine. The issue is that "import" property is not an actual esm its just reexport of cjs module.
![image](https://github.com/ts-rest/ts-rest/assets/35863331/b8a768af-3ecc-44ba-9a60-e1ed5f9bb6fe)
![image](https://github.com/ts-rest/ts-rest/assets/35863331/512694b0-6119-4670-ac74-e6ab1d1f0f97)

### Code reproduction

https://github.com/DataDog/import-in-the-middle/issues/107

### ts-rest version

3.45.2

**Comment by Gabrola** [comment]
It is a very common strategy to create an ESM wrapper for a CJS module (called faux ESM) and is actually recommended (see [this](https://nodejs.org/docs/latest-v22.x/api/packages.html#approach-1-use-an-es-module-wrapper)). So this is what the ".cjs.mjs" files are. The pure/true ESM files defined in "exports.module" are only used by bundlers and are there to help with tree shaking in order to reduce the size of frontend packages.

Our libraries work in all environments and configurations, so there is nothing to fix or change really and it's a problem with `import-in-the-middle` for sure.
