### ISSUE TITLE
@ts-rest/fastify pathPrefixes not working with nested contracts/routers

### ISSUE THREAD

**Issue by rkreienbuehl** [ts-rest/ts-rest#617]
### Describe the bug

only pathPrefixes set on the deepest level of a contract are used, upper level pathPrefixes are ignored, see reproduction script.
My ts-rest version is `3.45.2` and the fastify version is `4.28.0`.

Also I get a type error on `test: r1` but don^t have any clue why:

```
Type 'InitialisedRouter<RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>>' is not assignable to type 'InitialisedRouter<RecursivelyApplyOptions<RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>, { ...; }>> | RecursiveRouterObj<...>'.
  Type 'InitialisedRouter<RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>>' is not assignable to type 'InitialisedRouter<RecursivelyApplyOptions<RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>, { ...; }>>'.
    Types of property 'contract' are incompatible.
      Type 'RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>' is not assignable to type 'RecursivelyApplyOptions<RecursivelyApplyOptions<{ all: { method: "GET"; path: "/"; responses: { 200: ZodObject<{ data: ZodArray<ZodString, "many">; }, "strip", ZodTypeAny, { data: string[]; }, { data: string[]; }>; }; }; }, { ...; }>, { ...; }>'.ts(2322)
server.data.ts(399, 7): The expected type comes from property 'test' which is declared here on type 'RecursiveRouterObj<RecursivelyApplyOptions<{ test: RecursivelyApplyOptions<{ all: ...; }, { pathPrefix: "/test"; }>; }, { pathPrefix: "/first"; }>>'
```

### How to reproduce

start a ts-rest-fastify server according to the reproduction script:

Log output: `[ts-rest] Initialized GET /test/`

### Expected behavior

Log output should be `[ts-rest] Initialized GET /first/test/` and the route should listen to this.

### Code reproduction

```ts
const server = Fastify();

  const c = initContract();
  const s = initServer();

  const c1 = c.router(
    {
      all: {
        method: 'GET',
        path: '/',
        responses: {
          200: z.object({
            data: z.array(z.string())
          })
        }
      }
    },
    { pathPrefix: '/test' }
  );

  const c2 = c.router(
    {
      test: c1
    },
    { pathPrefix: '/first' }
  );

  const r1 = s.router(c1, {
    all: async () => {
      return {
        status: 200,
        body: { data: ['test1', 'test2'] }
      };
    }
  });

  const r2 = s.router(c2, {
    test: r1
  });

  s.registerRouter(c2, r2, server, {
    logInitialization: true,
    responseValidation: true
  });

  const start = async () => {
    try {
      await server.listen({ port: Number.parseInt(process.env.PORT || '9900') });
    } catch (err) {
      server.log.error(err);
      process.exit(1);
    }
  };

  start();
```

### ts-rest version

3.45.2

**Comment by Gabrola** [comment]
@rkreienbuehl If you make this change it should fix both the incorrectly initialized route and the type error.

```typescript
// before
const r1 = s.router(c1, {

// after
const r1 = s.router(c2.test, {
```

The problem is that when you pass `c1` directly, the router does not see the path prefix defined in `c2`. This is also the cause for the type error.

Technically this should not happen because you pass `c2` to ` s.registerRouter`, but this is just a peculiarity with just the fastify library due to how we construct the routers internally. I'd be fine with this if the type error was easy to understand, but at the moment it's not super intuitive so I will keep this issue open and try to find a way to fix this from the library's end.

**Comment by Gabrola** [comment]
@rkreienbuehl If you make this change it should fix both the incorrectly initialized route and the type error.

```typescript
// before
const r1 = s.router(c1, {

// after
const r1 = s.router(c2.test, {
```

The problem is that when you pass `c1` directly, the router does not see the path prefix defined in `c2`.

Technically this should not happen because you pass `c2` to ` s.registerRouter`, but this is just a peculiarity with just the fastify library due to how we construct the routers internally. I'd be fine with this if the type error was easy to understand, but at the moment it's not super intuitive so I will keep this issue open and try to find a way to fix this from the library's end.

**Comment by Gabrola** [comment]
@rkreienbuehl If you make this change it should fix both the incorrectly initialized route and the type error.

```typescript
// before
const r1 = s.router(c1, {

// after
const r1 = s.router(c2.test, {
```

The problem is that when you pass `c1` directly, the router does not see the path prefix defined in `c2`.

Technically this should not happen because you pass `c2` to `s.registerRouter`, but this is a peculiarity with just the fastify library due to how we construct the routers internally. I'd be fine with this if the type error was easy to understand, but at the moment it's not super intuitive so I will keep this issue open and try to find a way to fix this from the library's end.

**Comment by rkreienbuehl** [comment]
A colleague of mine did a quick investigation into the code and found a solution for the `pathPrefix` problem. He made a pull-request #619 that fixes this. With the fix, you don't have to do this `const r1 = s.router(c2.test, {`.
The issue with the typings also is present in ts-rest/express.

**Comment by guillaume-docquier-vention** [comment]
@rkreienbuehl do you mean that your fix would fix the following?
I'm trying to split contracts and routers as well, using path prefixes

```ts
import { initContract } from "@ts-rest/core"
import { initServer } from "@ts-rest/express"
import { z } from "zod"

export const authContract = initContract().router(
  {
    login: {
      method: "POST",
      path: `/login`,
      body: z.object({
        email: z.string(),
        password: z.string(),
      }),
      responses: {
        200: z.object({
          token: z.string(),
        }),
      },
    },
  },
  {
    pathPrefix: "/auth",
  },
)

export const authServer = initServer().router(authContract, {
  login: async () => {
    return {
      status: 200,
      body: {
        token: "secret token",
      },
    }
  },
})

export const contract = initContract().router(
  {
    auth: authContract,
  },
  {
    pathPrefix: "/api",
  },
)

export const router = initServer().router(contract, {
  // Error TS2322
  // Types of property login are incompatible.
  // The types of tsRestRoute.path are incompatible between these types.
  // Type "/api/auth/login" is not assignable to type "/auth/login"
  auth: authServer,
})
```

**Comment by guillaume-docquier-vention** [comment]
I looked at the fix, it's a 1-liner in `ts-rest/fastify`, so most likely not fixing express.

I created another issue here: https://github.com/ts-rest/ts-rest/issues/626

**Comment by Gabrola** [comment]
@rkreienbuehl @guillaume-docquier-vention see https://github.com/ts-rest/ts-rest/issues/626#issuecomment-2241319140
