### ISSUE TITLE
The inferred type of 'router' cannot be named without a reference

### ISSUE THREAD

**Issue by shawnmclean** [ts-rest/ts-rest#630]
### Describe the bug

I'm following the [Serverless Defining Router](https://ts-rest.com/docs/serverless/routers) page, using `tsr.router`

When exporting the route, I'm getting the following error:

```

The inferred type of 'usersRouter' cannot be named without a reference to '../../../../../node_modules/@ts-rest/serverless/src/lib/types'. This is likely not portable. A type annotation is necessary.

```

I found usage of this code in [another repo](https://github.com/tokens-studio/graph-engine/blob/437dc37f1ca95c0d04fbeda2402aec00871853d7/packages/ui/src/api/controllers/graph.ts#L10), checked out the code, ran `yarn` and then had the same typings error.

Similar bug to: https://github.com/ts-rest/ts-rest/issues/391

### How to reproduce

See this PR: https://github.com/shawnmclean/sovoli/pull/18/files#diff-303e5e3b866dec03b2ba9430273704f6236c221bba2e998d28384ffd7c977554R9

You can see where the CI throws the same error: 

https://github.com/shawnmclean/sovoli/actions/runs/9996744143/job/27631767968?pr=18#step:7:36

### Code reproduction

```
import { tsr } from "@ts-rest/serverless/next";

export const usersRouter = tsr.router<typeof contract.users, Context>(
  contract.users,
  {
    getUser: async (args) => {
     ...
    },
  }
);
```

### ts-rest version

    "@ts-rest/core": "3.45.2",
    "@ts-rest/serverless": "3.45.2",

**Comment by Gabrola** [comment]
@shawnmclean This error happens when you try to emit declarations when compiling with `tsc`.

Just curious to know... are you exporting the router and compiling it to be used by another package or app? Or are you just compiling it as part of the app to run it directly?

In the latter case, you can just set `declarations: false` in your tsconfig so that `tsc` does not emit any `d.ts` files. These will not be needed anyway if you are just compiling to run the code directly.

Ideally, we'd prefer to export as little as possible of the internal types of the library as that makes it much easier to do backwards compatible changes in the future.
