### ISSUE TITLE
Add contract options typings for keys

### ISSUE THREAD

**Issue by guillaume-docquier-vention** [ts-rest/ts-rest#635]
**Is your feature request related to a problem? Please describe.**
When creating a contract, the options keys are not typed. You can give any property and you also don't get any autocompletion.

**Describe the solution you'd like**
I'd like to get autocompletion and type validation on the contract options

**Describe alternatives you've considered**
N/A

**Additional context**
Here is some code:
```ts
import { initContract } from "@ts-rest/core"
import { z } from "zod"

export const authContract = initContract().router(
  {
    login: {
      method: "POST",
      path: `/login`,
      body: z.object({
        email: z.string(),
        password: z.string(),
      }),
      responses: {
        200: z.object({
          token: z.string(),
        }),
      },
    },
  },
  {
    // There no autocompletion here
    strictStatusCodes: 1, // TS2322: Type number is not assignable to type boolean | undefined, as it should
    pathPrefix: 1, // TS2322: Type number is not assignable to type string, as it should
    invalidKey: "but no error", // invalidKey is not valid, but typescript allows it
  },
)
```

![image](https://github.com/user-attachments/assets/658f2b2c-08a4-41f9-8bca-f83a19890c71)

![image](https://github.com/user-attachments/assets/6b19a6c4-962a-42e9-bd01-74e8eafd745a)

- Node 22.3.0
- Npm 10.8.1
- Typescript 5.5.3
- @ts-rest/core 3.46.0
- @ts-rest/express 3.46.0
- Webstorm

**Comment by Gabrola** [comment]
Not sure why autocomplete is not working for you. It's working for me, also on WebStorm. Also tested outside of the ts-rest repo, and in app repo consuming ts-rest.

![Screenshot 2024-07-22 160829](https://github.com/user-attachments/assets/f296c942-a77a-4890-a9b7-dd26ab2cf81d)

The case with `invalidKey`; it's not giving an error because the previous errors are already causing a type mismatch on the `options` object. If you remove, or fix those, it technically fixes the type but then you get an error because of `Object literal may only specify known properties`.

![Screenshot 2024-07-22 160857](https://github.com/user-attachments/assets/c2a3f83d-bec5-4f29-a3cd-9b154486f60a)

This is a separate error because defining extra keys is not a type compatibility problem, but rather a case where TS does not allow object literals to specify extra properties. If you send an object with any extra keys, rather than an object literal, TS would not complain.

![Screenshot 2024-07-22 161809](https://github.com/user-attachments/assets/65ddde10-a2c4-4933-a941-b3b791af3f01)

**Comment by guillaume-docquier-vention** [comment]
This is strange, if there's a valid property or no property, I don't get suggestions via ctrl+space, nor if I type
![image](https://github.com/user-attachments/assets/86bb99b2-d132-4ddc-bcde-1845522d044f)
![image](https://github.com/user-attachments/assets/8f140c1f-73b0-454e-9f46-d865fc390120)

But if there is an invalid property, then I get completion and suggestions:
![image](https://github.com/user-attachments/assets/163b44ee-1aba-4a66-8778-3d70e28c9a51)
![image](https://github.com/user-attachments/assets/5b4cd029-841c-4330-a1c3-9e5d3072ca09)

As for the invalid key, I observed something similar. There's no error only if there's at least 1 valid key:
![image](https://github.com/user-attachments/assets/cc6aba23-a962-4758-b735-7b3ebf7114fc)
![image](https://github.com/user-attachments/assets/06904475-ba3e-46ab-b002-dc5a741ca507)

This sounds like a problem on my side. This is highly unusual, I've never seen this happen.
Feel free to close if you don't see this in webstorm on your side.

**Comment by Gabrola** [comment]
Could be TS 5.5. Although TS 5.5 works for me, I think some IDEs still do not fully support it yet. Try downgrading to TS 5.4, and see if that fixes it.

**Comment by guillaume-docquier-vention** [comment]
WebStorm 2024.1.5
Same behavior with Typescript 5.4.5

I'm hoping this is just my installation, not sure which setting would change this behaviour.
