### ISSUE TITLE
`@ts-rest/core` body should be optional for DELETE endpoints

### ISSUE THREAD

**Issue by rkreienbuehl** [ts-rest/ts-rest#669]
### Describe the bug

The ts-rest typings require you to add a body for a DELETE endpoint. As per rest definition, a body is not required on DELETE endpoints.

### How to reproduce

Define a contract with a DELETE endpoint without defining a body will get you a type error.

### Expected behavior

Typings should be that body is optional on DELETE endpoints.

### Code reproduction

```ts
import { initContract } from '@ts-rest/core';
import { z } from 'zod';

const c = initContract();

export const contract = c.router(
  {
    delete: {
      method: 'DELETE',
      path: '/:id',
      pathParams: z.object({
        id: z.string(),
      }),
      responses: {
        204: c.noBody(),
      },
    },
  },
  { pathPrefix: '/api/test', strictStatusCodes: true }
);
```

### ts-rest version

v3.49.3

**Comment by Gabrola** [comment]
There's really no such thing as a REST spec, and in reality the HTTP spec does not explicitly mention that you must or mustn't pass a body for any HTTP method really. So you're technically allowed to pass a body even in a GET, and you send empty POST request bodies. However, since the spec does indeed mention that behavior may be undefined if a body is passed for HEAD, GET or DELETE.

I think it's better in general to define behavior explicitly by setting `body: c.noBody()`, but in the case of DELETE, I think it's better to be consistent and treat DELETE similarly to GET in ts-rest since the general expectation that DELETEs have no body. Obviously, can't take away the ability to pass a body now, but should at least allow it to be optional.
