### ISSUE TITLE
Unable to set access token in header with React Query client

### ISSUE THREAD

**Issue by namukang** [ts-rest/ts-rest#675]
### Describe the bug

I'm trying to use `ts-rest`'s React Query client (https://ts-rest.com/docs/react-query/v5-setup).

The requests I'm making need to include an `Authorization` header with `Bearer ${token}`, where `token` is an asynchronously generated access token.

Since access tokens expire after some time, the header needs to be set at the time of the request with a valid token. 

The issue that I'm running into is that it doesn't seem possible to set the header at the time of the request when using `ts-rest`'s React Query.

### Option 1: `baseHeaders` in `initTsrReactQuery`

```typescript
export const tsr = initTsrReactQuery(contract, {
  baseUrl: 'http://localhost:3333',
  baseHeaders: {},
});
```

The header can't be set as a base header on `initTsrReactQuery` because `<tsr.ReactQueryProvider>` wraps the application so the same header will be used throughout the entire lifecycle of the application, during which access tokens may expire.

### Option 2: `headers` in `useQuery`

```typescript
const { data, isPending } = tsr.posts.get.useQuery({ 
    queryKey: ['posts'],
    queryData: {
      headers: {
        authorization: `Bearer ${token}`,
      },
    },
});
```

The header can't be set when calling `useQuery` because while the token may be valid now, it may be expired when re-fetching the data at a later time.

### Suggestion

It seems that the only way to support setting the header at the time the request is made is to allow passing in a function to `baseHeaders` or `headers`. (In my case, it'd need to support asynchronous functions as well since the token is generated asynchronously.)

Comparison: `tRPC` supports passing in a function to set custom headers: https://trpc.io/docs/client/headers

It seems that I've run into a limitation in the React Query client made by `ts-rest`, but I'm new to `ts-rest` and React Query / Tanstack Query so please let me know if I'm misunderstanding something or if there's a solution I'm overlooking!

### ts-rest version

3.50.0

**Comment by Gabrola** [comment]
You can pass a function to `baseHeaders`, but not to `headers` for individual queries or mutations. This is on purpose, because passing any auth tokens either directly as a string, or a function will technically mean you need to include it as part of your Query Key somehow. 

I believe the common and recommended approach is to handle all auth stuff outside of React Land entirely. So all the auth stuff, handling 401 errors, etc. should happen opaquely to your React code. You can achieve this using a [custom client](https://ts-rest.com/docs/core/custom). You can change any parameters going to `tsRestFetchApi()`, and you can intercept the response to handle auth errors, token refresh, etc. before passing the response back to the client.

I think the TSR RQ docs need to clearly indicate this though, so I'll make sure to edit the docs now, and maybe add some example in the repo to show how auth is done later.

**Comment by Gabrola** [comment]
You can pass a function to `baseHeaders`, but not to `headers` for individual queries or mutations. This is on purpose because passing any auth tokens as a string means you need to somehow encapsulate it as part of your Query Key. Furthermore, passing any kind of function, whether for auth or other purposes, just makes the query non-deterministic and complicates formulating a well functioning query key.

I believe the common and recommended approach is to handle all auth stuff outside of React land entirely. So passing tokens, handling auth errors, etc. should happen opaquely to your React code. You can achieve this using a [custom client](https://ts-rest.com/docs/core/custom). You can change any parameters going to `tsRestFetchApi()`, and you can intercept the response to handle auth errors, token refresh, etc. before passing the response back to the client. This provides very similar functionality to axios interceptors.

I think the TSR RQ docs need to clearly indicate this though, so I'll make sure to edit the docs now, and maybe add some example in the repo to show how auth is done later.

**Comment by namukang** [comment]
Thanks Gabrola! Appreciate the clarification and the link to the custom client docs.

For anyone who stumbles on this issue in the future, the custom client docs that Gabrola linked has an example on how to generate an access token asynchronously (e.g. when using auth from Firebase or Supabase) since `baseHeaders` takes in functions but not async functions: https://ts-rest.com/docs/core/custom#instantiate-the-client-but-access-a-token-during-runtime
