### ISSUE TITLE
Init Client Showing RecursivelyApplyOptions error when importing from another package in workspace

### ISSUE THREAD

**Issue by vandettagroup** [ts-rest/ts-rest#717]
### Describe the bug

As I described, I get this error when I try to import contract from another package inside of PNPM Workspace:

```
Argument of type 'RecursivelyApplyOptions<{ auth: RecursivelyApplyOptions<{ signInWithEmail: ...; }, {}>; }, {}>' is not assignable to parameter of type 'AppRouter'.
  Property 'auth' is incompatible with index signature.
    Type 'RecursivelyApplyOptions<RecursivelyApplyOptions<{ signInWithEmail: { method: "POST"; path: "/auth/signin-with-email"; body: ZodObject<{ email: ZodString; password: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>; responses: { ...; }; }; }, {}>, {}>' is not assignable to type 'AppRouter | AppRoute'.
      Type 'RecursivelyApplyOptions<RecursivelyApplyOptions<{ signInWithEmail: { method: "POST"; path: "/auth/signin-with-email"; body: ZodObject<{ email: ZodString; password: ZodString; }, "strip", ZodTypeAny, { ...; }, { ...; }>; responses: { ...; }; }; }, {}>, {}>' is not assignable to type 'AppRouter'.
```

tsconfig for front end app:

```ts
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "ESNext",
    "esModuleInterop": true,
    "noUncheckedIndexedAccess": true,
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "downlevelIteration": true,
    "noFallthroughCasesInSwitch": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    "strictNullChecks": true,
    "paths": {
      "@/*": ["./src/*"]
    },
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" },{ "path": "../server" }]
}


```

tsconfig for server:

```ts
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "strictNullChecks": true,
    "noFallthroughCasesInSwitch": false,
    "noUnusedLocals": true,
    "composite": true,
    "noUnusedParameters": true,
    "paths": {
      "@src/*": ["src/*"]
    },
    "strict": true
  }
}
```

If I remove the `c.type()` and I use zod defined schema as a response everything is fine

Versions I am using:

```ts
"@ts-rest/core": "^3.51.0",
"@ts-rest/nest": "^3.51.0",
"typescript": "^5.7.2"
```

### How to reproduce

Import contract from other app inside of PNPM Workspace

### Expected behavior

I expect types to work when using `c.type`

### Code reproduction

Contract definition in the backend:

```ts
import { initContract } from "@ts-rest/core";
import { z } from "zod";

import { SignInWithEmailResponse } from "@src/resources/auth/auth.service";

const c = initContract();

const index = c.router({
  signInWithEmail: {
    method: "POST",
    path: "/auth/signin-with-email",
    body: z.object({
      email: z.string().email(),
      password: z.string().min(8),
    }),
    responses: {
      200: c.type<SignInWithEmailResponse>(),
    },
  },
});

export default index;
```

Implementation in the client:

```ts
import { initClient } from '@ts-rest/core';
import axios, { AxiosError, AxiosResponse, isAxiosError, Method } from 'axios';
import contract from '@riderly/server/src/contracts';

import C from '@/constants';

export const tsRestClient = initClient(contract, {
   
    baseUrl: `${C.VITE_APP_NEST_SERVER}/v2`,
    credentials: 'include',
    validateResponse: true,
});
```

### ts-rest version

3.51.0

**Comment by vandettagroup** [comment]
fixed by downgrading to `3.49.3`

**Comment by vandettagroup** [comment]
fixed by downgrading to 3.49.3

**Comment by denlahodnyi** [comment]
I had the same problem. I'm not very good at Typescript, but as far as I understood, the main reason is the usage of opaque types with `unique symbol ` in @ts-rest/core/src/lib/dsl.d.ts.
In my case, I have workspace A with @ts-rest/core and workspace B with @ts-rest/nest. This ts-rest/nest uses ts-rest/core under the hood, so it MUST resolve to the same dependency as workspace A. This is because opaque types from the different files won’t be considered the same.

There are two working (in my case) solutions:
1. Check why PNPM doesn’t lead to the same @ts-rest/core for both @ts-rest/nest in workspace B and workspace A.
For example, I discovered such dependencies:
`node_modules/.pnpm/@ts-rest+core@3.51.0_@types+node@22.10.1_zod@3.23.8/node_modules/@ts-rest/core/src/lib/dsl.d.ts` in workspace A and `node_modules/.pnpm/@ts-rest+core@3.51.0_@types+node@20.17.0_zod@3.23.8/node_modules/@ts-rest/core/src/lib/dsl.d.ts` in workspace B. As you can see pnpm deduplicates them because of different @types/node versions. After updating it to 22.10.1 in workspace B the problem has gone.
2. Remove @ts-rest/nest from workspace B. Install it with @ts-rest/core in workspace A and export all @ts-rest/nest staff from the same workspace. In that case, @ts-rest/nest will guarantee to use types from the same @ts-rest/core

**Comment by RomainSF** [comment]
Can we figure out the root cause or provide some typing to bypass the issue?

It's still happening when importing from a shared library vs direct.
